image: Visual Studio 2022
version: 2.0.{build}
branches:
  only:
  - master

configuration: Release

before_build:
  - nuget restore 

build:
  verbosity: minimal
  project: BigSharp.sln

test:
  assemblies:
    - '**\*.Tests.dll'